version: '3'
services:
  db-blue:
    build:
      context: ./db
      shm_size: '100gb'
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=sirene
      - POSTGRES_USER=sirene
      - POSTGRES_PASSWORD=sirene
    networks:
       - traefik
  postgrest:
    build: 
      context: ./api
      args: 
        - POSTGREST_VERSION=v7.0.1
    environment:
      - POSTGRES_DB_HOST=db-blue
      - POSTGRES_DB=sirene
      - POSTGRES_USER=sirene
      - POSTGRES_PASSWORD=sirene
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postgrest.rule=Host(`localhost`)"
      - "traefik.http.routers.postgrest.entrypoints=postgrest"
      - "traefik.port=3000"
    depends_on:
      - db-blue
networks:
    traefik:
        external:
            name: backend-siren_backendsiren
